name: Build Picons snp-full
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends --no-install-suggests git xz-utils binutils pngquant imagemagick librsvg2-bin jq
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Build snp-full picons
      run: |
        bash 2-build-picons.sh snp-full
    - name: Upload snp-full picons
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'build-output/binaries-snp-full/*'
