name: Build Picons srp-full
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends --no-install-suggests git xz-utils binutils pngquant imagemagick librsvg2-bin jq
    - name: Checkout the repository
      uses: actions/checkout@master
    - name: Build srp-full picons
      run: |
        bash 2-build-picons.sh srp-full
    - name: Upload srp-full picons
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: 'build-output/binaries-srp/*'
