name: Create Release
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get current version
        id: version
        run: |
          hash=$(git rev-parse --short HEAD)
          echo "version=$(date --utc --date=@$(git show -s --format=%ct $hash) +'%Y-%m-%d--%H-%M-%S')" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{steps.version.outputs.version}}
          name: ${{steps.version.outputs.version}}
          body: |
            Picon packages can take up to an hour to appear here...
          draft: false
          prerelease: false

  build-snp-full:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends --no-install-suggests git xz-utils binutils pngquant imagemagick librsvg2-bin jq
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Build snp-full picons
      run: |
        bash 2-build-picons.sh snp-full
    - name: Upload snp-full picons
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'build-output/binaries-snp-full/*'

  build-snp:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends --no-install-suggests git xz-utils binutils pngquant imagemagick librsvg2-bin jq
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Download channellists
      run: |
        curl -fsSL "https://github.com/picons/channellists/archive/master.tar.gz" | tar xzf - -C "./build-input" --strip-components=1
    - name: Build snp-13e.19e.23e.28e picons
      run: |
        mv ./build-input/13e.19e.23e.28e ./build-input/enigma2
        bash 1-build-servicelist.sh snp
        bash 2-build-picons.sh snp -13e.19e.23e.28e
        rm -rf ./build-input/enigma2
    - name: Upload snp-13e.19e.23e.28e picons
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'build-output/binaries-snp/*'
    - name: Build snp-ziggo picons
      run: |
        mv ./build-input/ziggo ./build-input/enigma2
        bash 1-build-servicelist.sh snp
        bash 2-build-picons.sh snp -ziggo
        rm -rf ./build-input/enigma2
    - name: Upload snp-ziggo picons
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'build-output/binaries-snp/*'

  build-srp-full:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends --no-install-suggests git xz-utils binutils pngquant imagemagick librsvg2-bin jq
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Build srp-full picons
      run: |
        bash 2-build-picons.sh srp-full
    - name: Upload srp-full picons
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'build-output/binaries-srp-full/*'

  build-srp:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends --no-install-suggests git xz-utils binutils pngquant imagemagick librsvg2-bin jq
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Download channellists
      run: |
        curl -fsSL "https://github.com/picons/channellists/archive/master.tar.gz" | tar xzf - -C "./build-input" --strip-components=1
    - name: Build srp-13e.19e.23e.28e picons
      run: |
        mv ./build-input/13e.19e.23e.28e ./build-input/enigma2
        bash 1-build-servicelist.sh srp
        bash 2-build-picons.sh srp -13e.19e.23e.28e
        rm -rf ./build-input/enigma2
    - name: Upload srp-13e.19e.23e.28e picons
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'build-output/binaries-srp/*'
    - name: Build srp-ziggo picons
      run: |
        mv ./build-input/ziggo ./build-input/enigma2
        bash 1-build-servicelist.sh srp
        bash 2-build-picons.sh srp -ziggo
        rm -rf ./build-input/enigma2
    - name: Upload srp-ziggo picons
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'build-output/binaries-srp/*'
